### ISSUE TITLE
Support configuration file

### ISSUE THREAD

**Issue by donny-dont** [dogma-dart/dogma-codegen#16]
The number of options to build is way too high. Using a config will make this easier especially when the options are likely to increase.

Suggestion is to create a .dogma.yml that will contain configuration options on a per library basis. As an example something like this may be effective.

```
convert:
  library: lib/converters.dart
  sourceDirectory: lib/src/converters
  options:
    generateEncoders: false
```
